site_name: Workshops

nav:
  - Clean Architecture: 
      - clean-architecture/index.md
      - Introduction: clean-architecture/01_introduction.md
      - Principles:
        - Design Principles:
          - Overview: clean-architecture/02_design_principles.md
          - Single Responsability Principle: clean-architecture/03_single_responsability_principle.md
          - Open Closed Principle: clean-architecture/04_open_closed_principle.md
          - Liskov Substitution Principle: clean-architecture/05_liskov_substitution_principle.md
          - Interface Segregation Principle: clean-architecture/06_interface_segregation_principle.md
          - Dependency Inversion Principle: clean-architecture/07_dependency_inversion_principle.md
        - Component Principles:
          - Overview: clean-architecture/08_component_principles.md
          - Component Cohesion: clean-architecture/09_component_cohesion.md
          - Component Coupling: clean-architecture/10_component_coupling.md
      - Architectural Patterns:
        - Overview: clean-architecture/11_architectural_patterns.md
        - Layered Architecture: clean-architecture/12_layered_architecture.md
        - Onion Architecture: clean-architecture/13_onion_architecture.md
        - Hexagonal Architecture: clean-architecture/14_hexagonal_architecture.md
        - Clean Architecture: clean-architecture/15_clean_architecture.md


      #   - Layered Architecture: clean-architecture/15_layered_architecture.md
      #   - Hexagonal Architecture: clean-architecture/16_hexagonal_architecture.md
      #   - Microservices: clean-architecture/17_microservices.md
      #   - Event-Driven Architecture: clean-architecture/18_event_driven_architecture.md 
      - Resources: clean-architecture/00_resources.md
      - Template: clean-architecture/template.md

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  features:
  - navigation.footer
  - navigation.instant
  - navigation.tabs
  - navigation.path
  - navigation.indexes
  - navigation.top
  - content.code.copy
  - content.code.select

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue  

extra_css:
  - css/style.css

plugins:
  - search
  - glightbox
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: puml
      local_file_inclusion: true
      request_timeout: 300
      verify_ssl: true
      verbose: true
      theme:
        enabled: true
        light: nord/day
        dark: nord/night
      cache:
        backend: local
        local:
          path: "~/.cache/mkdocs_puml"
          join_project_name: true
      interaction:
        enabled: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details