site_name: Workshops

nav:
  - Clean Architecture: 
      - Introduction: clean-architecture/01_introduction.md
      - Principles: clean-architecture/02_design_principles.md
      - SOLID: 
        - Single Responsability Principle: clean-architecture/03_single_responsability_principle.md
        - Open Closed Principle: clean-architecture/04_open_closed_principle.md
        - Liskov Substitution Principle: clean-architecture/05_liskov_substitution_principle.md

theme:
  name: material
  features:
    - navigation.expand